steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ml-sales-prediction-satyam', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ml-sales-prediction-satyam']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ml-sales-prediction
      - --image=gcr.io/$PROJECT_ID/ml-sales-prediction-satyam
      - --platform=managed
      - --region=us-central1
      - --allow-unauthenticated

images:
  - gcr.io/$PROJECT_ID/ml-sales-prediction-satyam

