apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: ml-sales-pipeline-satyam
description: Canary rollout pipeline for ML app
serialPipeline:
  stages:
    - targetId: dev
      strategy:
        canary:
          runtimeConfig:
            cloudRun:
              automaticTrafficControl: true
          canaryDeployment:
            percentages: [25, 75]
            verify: false
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Dev environment for ML app
run:
  location: projects/faa-gcp-training-14-kfa-0808/locations/us-central1